FROM alpine

RUN apk --update upgrade && \
    apk add ca-certificates && \
    update-ca-certificates

RUN adduser -h /home/ui -D ui ui
RUN mkdir /Users

COPY ./web_ui /home/ui/
RUN chmod +x /home/ui/web_ui

COPY ./assets /home/ui/
COPY ./public /home/ui/

COPY ./database.yml /home/ui/database.yml

USER ui

ENTRYPOINT ["/home/ui/web_ui"]
